name: Deploy to Server

on:
  push:
    branches:
      - feature/exercicio-03

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          # Coloque os comandos de deploy aqui
          # Por exemplo, usando SSH para fazer o deploy para um servidor
          ssh user@your-server 'cd /path/to/your/app && git pull'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
